[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "fastform-api"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app/src"
DATABASE_URL = "sqlite:///app/fastform.db"
