#!/usr/bin/env python3
"""
CMS Formulary Data Ingestion Script

Creates comprehensive formulary data for testing with realistic Medicare Part D drug information.
In production, this would download actual CMS formulary files from:
https://www.cms.gov/medicare/prescription-drug-coverage/prescriptiondrugcovgenin/formularyfiles
"""

import logging
import sqlite3

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def create_database_schema(db_path: str) -> None:
    """Create the enhanced database schema for formulary data."""
    conn = sqlite3.connect(db_path)

    # Drop existing table to start fresh
    conn.execute("DROP TABLE IF EXISTS drug_rules")

    # Create enhanced schema for comprehensive formulary data
    conn.execute("""
        CREATE TABLE drug_rules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            dosage_form TEXT,
            strength_qty REAL,
            strength_unit TEXT,
            route TEXT,
            generic_name TEXT,
            brand_name TEXT,
            ndc TEXT,
            formulary_tier INTEGER,
            prior_authorization BOOLEAN DEFAULT 0,
            quantity_limit BOOLEAN DEFAULT 0,
            step_therapy BOOLEAN DEFAULT 0,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Create indexes for better search performance
    conn.execute("CREATE INDEX idx_name ON drug_rules(name)")
    conn.execute("CREATE INDEX idx_generic_name ON drug_rules(generic_name)")
    conn.execute("CREATE INDEX idx_brand_name ON drug_rules(brand_name)")
    conn.execute("CREATE INDEX idx_formulary_tier ON drug_rules(formulary_tier)")

    conn.commit()
    conn.close()
    logger.info("Enhanced database schema created successfully")


def load_comprehensive_formulary_data(db_path: str) -> None:
    """Load comprehensive sample formulary data representing a realistic
    Medicare Part D formulary."""

    # Comprehensive drug data representing real Medicare Part D coverage
    sample_drugs = [
        # Tier 1 - Generic Drugs (lowest cost)
        (
            "Acetaminophen",
            "tablet",
            325.0,
            "mg",
            "oral",
            "acetaminophen",
            "Tylenol",
            "50580-506-02",
            1,
            False,
            False,
            False,
        ),
        (
            "Acetaminophen",
            "tablet",
            500.0,
            "mg",
            "oral",
            "acetaminophen",
            "Tylenol Extra Strength",
            "50580-506-05",
            1,
            False,
            False,
            False,
        ),
        (
            "Ibuprofen",
            "tablet",
            200.0,
            "mg",
            "oral",
            "ibuprofen",
            "Advil",
            "50580-449-02",
            1,
            False,
            False,
            False,
        ),
        (
            "Ibuprofen",
            "tablet",
            400.0,
            "mg",
            "oral",
            "ibuprofen",
            "Motrin",
            "50580-449-04",
            1,
            False,
            False,
            False,
        ),
        (
            "Naproxen",
            "tablet",
            220.0,
            "mg",
            "oral",
            "naproxen sodium",
            "Aleve",
            "50580-507-11",
            1,
            False,
            True,
            False,
        ),
        (
            "Aspirin",
            "tablet",
            81.0,
            "mg",
            "oral",
            "aspirin",
            "Bayer Low Dose",
            "50580-165-81",
            1,
            False,
            False,
            False,
        ),
        (
            "Aspirin",
            "tablet",
            325.0,
            "mg",
            "oral",
            "aspirin",
            "Bayer",
            "50580-165-32",
            1,
            False,
            False,
            False,
        ),
        # Cardiovascular - Tier 1 Generics
        (
            "Lisinopril",
            "tablet",
            5.0,
            "mg",
            "oral",
            "lisinopril",
            "Prinivil",
            "68180-512-06",
            1,
            False,
            False,
            False,
        ),
        (
            "Lisinopril",
            "tablet",
            10.0,
            "mg",
            "oral",
            "lisinopril",
            "Zestril",
            "68180-512-01",
            1,
            False,
            False,
            False,
        ),
        (
            "Lisinopril",
            "tablet",
            20.0,
            "mg",
            "oral",
            "lisinopril",
            "Prinivil",
            "68180-512-02",
            1,
            False,
            False,
            False,
        ),
        (
            "Amlodipine",
            "tablet",
            2.5,
            "mg",
            "oral",
            "amlodipine besylate",
            "Norvasc",
            "68180-513-06",
            1,
            False,
            False,
            False,
        ),
        (
            "Amlodipine",
            "tablet",
            5.0,
            "mg",
            "oral",
            "amlodipine besylate",
            "Norvasc",
            "68180-513-01",
            1,
            False,
            False,
            False,
        ),
        (
            "Amlodipine",
            "tablet",
            10.0,
            "mg",
            "oral",
            "amlodipine besylate",
            "Norvasc",
            "68180-513-02",
            1,
            False,
            False,
            False,
        ),
        (
            "Metoprolol",
            "tablet",
            25.0,
            "mg",
            "oral",
            "metoprolol tartrate",
            "Lopressor",
            "68180-514-25",
            1,
            False,
            False,
            False,
        ),
        (
            "Metoprolol",
            "tablet",
            50.0,
            "mg",
            "oral",
            "metoprolol tartrate",
            "Lopressor",
            "68180-514-50",
            1,
            False,
            False,
            False,
        ),
        (
            "Metoprolol",
            "tablet",
            100.0,
            "mg",
            "oral",
            "metoprolol tartrate",
            "Lopressor",
            "68180-514-10",
            1,
            False,
            False,
            False,
        ),
        (
            "Simvastatin",
            "tablet",
            10.0,
            "mg",
            "oral",
            "simvastatin",
            "Zocor",
            "68180-515-10",
            1,
            False,
            False,
            False,
        ),
        (
            "Simvastatin",
            "tablet",
            20.0,
            "mg",
            "oral",
            "simvastatin",
            "Zocor",
            "68180-515-20",
            1,
            False,
            False,
            False,
        ),
        (
            "Simvastatin",
            "tablet",
            40.0,
            "mg",
            "oral",
            "simvastatin",
            "Zocor",
            "68180-515-40",
            1,
            False,
            False,
            False,
        ),
        # Diabetes - Mixed Tiers
        (
            "Metformin",
            "tablet",
            500.0,
            "mg",
            "oral",
            "metformin hydrochloride",
            "Glucophage",
            "68180-516-50",
            1,
            False,
            False,
            False,
        ),
        (
            "Metformin",
            "tablet",
            850.0,
            "mg",
            "oral",
            "metformin hydrochloride",
            "Glucophage",
            "68180-516-85",
            1,
            False,
            False,
            False,
        ),
        (
            "Metformin",
            "tablet",
            1000.0,
            "mg",
            "oral",
            "metformin hydrochloride",
            "Glucophage XR",
            "68180-516-10",
            1,
            False,
            False,
            False,
        ),
        (
            "Glipizide",
            "tablet",
            5.0,
            "mg",
            "oral",
            "glipizide",
            "Glucotrol",
            "68180-517-05",
            1,
            False,
            False,
            False,
        ),
        (
            "Glipizide",
            "tablet",
            10.0,
            "mg",
            "oral",
            "glipizide",
            "Glucotrol XL",
            "68180-517-10",
            1,
            False,
            False,
            False,
        ),
        (
            "Glyburide",
            "tablet",
            2.5,
            "mg",
            "oral",
            "glyburide",
            "Micronase",
            "68180-518-25",
            1,
            False,
            False,
            False,
        ),
        (
            "Glyburide",
            "tablet",
            5.0,
            "mg",
            "oral",
            "glyburide",
            "DiaBeta",
            "68180-518-05",
            1,
            False,
            False,
            False,
        ),
        # Tier 2 - Preferred Brand Drugs
        (
            "Atorvastatin",
            "tablet",
            10.0,
            "mg",
            "oral",
            "atorvastatin calcium",
            "Lipitor",
            "00071-0155-23",
            2,
            False,
            False,
            False,
        ),
        (
            "Atorvastatin",
            "tablet",
            20.0,
            "mg",
            "oral",
            "atorvastatin calcium",
            "Lipitor",
            "00071-0156-23",
            2,
            False,
            False,
            False,
        ),
        (
            "Atorvastatin",
            "tablet",
            40.0,
            "mg",
            "oral",
            "atorvastatin calcium",
            "Lipitor",
            "00071-0157-23",
            2,
            False,
            False,
            False,
        ),
        (
            "Clopidogrel",
            "tablet",
            75.0,
            "mg",
            "oral",
            "clopidogrel bisulfate",
            "Plavix",
            "00087-3270-41",
            2,
            False,
            False,
            True,
        ),
        (
            "Amlodipine/Benazepril",
            "capsule",
            2.5,
            "mg/10mg",
            "oral",
            "amlodipine/benazepril",
            "Lotrel",
            "00078-0364-15",
            2,
            False,
            False,
            False,
        ),
        # Respiratory - Mixed Tiers
        (
            "Albuterol",
            "inhaler",
            90.0,
            "mcg",
            "inhalation",
            "albuterol sulfate",
            "ProAir HFA",
            "59310-579-15",
            2,
            False,
            True,
            False,
        ),
        (
            "Albuterol",
            "solution",
            2.5,
            "mg/3mL",
            "nebulization",
            "albuterol sulfate",
            "Accuneb",
            "59310-580-03",
            1,
            False,
            False,
            False,
        ),
        (
            "Fluticasone",
            "nasal spray",
            50.0,
            "mcg",
            "nasal",
            "fluticasone propionate",
            "Flonase",
            "00173-0453-01",
            2,
            False,
            False,
            False,
        ),
        (
            "Montelukast",
            "tablet",
            10.0,
            "mg",
            "oral",
            "montelukast sodium",
            "Singulair",
            "00006-0711-54",
            2,
            False,
            False,
            False,
        ),
        (
            "Montelukast",
            "tablet",
            5.0,
            "mg",
            "oral",
            "montelukast sodium",
            "Singulair",
            "00006-0275-54",
            2,
            False,
            False,
            False,
        ),
        (
            "Budesonide/Formoterol",
            "inhaler",
            80,
            "mcg/4.5mcg",
            "inhalation",
            "budesonide/formoterol",
            "Symbicort",
            "00186-0372-20",
            3,
            True,
            True,
            False,
        ),
        # Antibiotics - Tier 1 & 2
        (
            "Amoxicillin",
            "capsule",
            250.0,
            "mg",
            "oral",
            "amoxicillin",
            "Amoxil",
            "00777-3105-02",
            1,
            False,
            False,
            False,
        ),
        (
            "Amoxicillin",
            "capsule",
            500.0,
            "mg",
            "oral",
            "amoxicillin",
            "Amoxil",
            "00777-3107-02",
            1,
            False,
            False,
            False,
        ),
        (
            "Amoxicillin/Clavulanate",
            "tablet",
            500,
            "mg/125mg",
            "oral",
            "amoxicillin/clavulanate",
            "Augmentin",
            "00029-6080-22",
            2,
            False,
            False,
            False,
        ),
        (
            "Azithromycin",
            "tablet",
            250.0,
            "mg",
            "oral",
            "azithromycin",
            "Zithromax",
            "00069-3050-30",
            2,
            False,
            False,
            False,
        ),
        (
            "Ciprofloxacin",
            "tablet",
            250.0,
            "mg",
            "oral",
            "ciprofloxacin",
            "Cipro",
            "50458-220-01",
            2,
            False,
            False,
            False,
        ),
        (
            "Ciprofloxacin",
            "tablet",
            500.0,
            "mg",
            "oral",
            "ciprofloxacin",
            "Cipro",
            "50458-220-05",
            2,
            False,
            False,
            False,
        ),
        (
            "Doxycycline",
            "capsule",
            100.0,
            "mg",
            "oral",
            "doxycycline hyclate",
            "Vibramycin",
            "00069-0970-95",
            1,
            False,
            False,
            False,
        ),
        # Mental Health - Higher Tiers with Restrictions
        (
            "Sertraline",
            "tablet",
            25.0,
            "mg",
            "oral",
            "sertraline hydrochloride",
            "Zoloft",
            "00049-4960-66",
            2,
            False,
            False,
            False,
        ),
        (
            "Sertraline",
            "tablet",
            50.0,
            "mg",
            "oral",
            "sertraline hydrochloride",
            "Zoloft",
            "00049-4900-66",
            2,
            False,
            False,
            False,
        ),
        (
            "Sertraline",
            "tablet",
            100.0,
            "mg",
            "oral",
            "sertraline hydrochloride",
            "Zoloft",
            "00049-4910-66",
            2,
            False,
            False,
            False,
        ),
        (
            "Escitalopram",
            "tablet",
            5.0,
            "mg",
            "oral",
            "escitalopram oxalate",
            "Lexapro",
            "00456-2005-01",
            2,
            False,
            False,
            False,
        ),
        (
            "Escitalopram",
            "tablet",
            10.0,
            "mg",
            "oral",
            "escitalopram oxalate",
            "Lexapro",
            "00456-2010-01",
            2,
            False,
            False,
            False,
        ),
        (
            "Escitalopram",
            "tablet",
            20.0,
            "mg",
            "oral",
            "escitalopram oxalate",
            "Lexapro",
            "00456-2020-01",
            2,
            False,
            False,
            False,
        ),
        (
            "Lorazepam",
            "tablet",
            0.5,
            "mg",
            "oral",
            "lorazepam",
            "Ativan",
            "00008-0064-01",
            3,
            True,
            True,
            True,
        ),
        (
            "Lorazepam",
            "tablet",
            1.0,
            "mg",
            "oral",
            "lorazepam",
            "Ativan",
            "00008-0063-01",
            3,
            True,
            True,
            True,
        ),
        (
            "Lorazepam",
            "tablet",
            2.0,
            "mg",
            "oral",
            "lorazepam",
            "Ativan",
            "00008-0065-01",
            3,
            True,
            True,
            True,
        ),
        (
            "Alprazolam",
            "tablet",
            0.25,
            "mg",
            "oral",
            "alprazolam",
            "Xanax",
            "00009-0090-01",
            3,
            True,
            True,
            True,
        ),
        (
            "Alprazolam",
            "tablet",
            0.5,
            "mg",
            "oral",
            "alprazolam",
            "Xanax",
            "00009-0029-01",
            3,
            True,
            True,
            True,
        ),
        # Insulin and Diabetes Injectables - Tier 3 with Restrictions
        (
            "Insulin Lispro",
            "injection",
            100.0,
            "units/mL",
            "subcutaneous",
            "insulin lispro",
            "Humalog",
            "00002-7510-01",
            3,
            True,
            True,
            False,
        ),
        (
            "Insulin Aspart",
            "injection",
            100.0,
            "units/mL",
            "subcutaneous",
            "insulin aspart",
            "NovoLog",
            "00169-7501-11",
            3,
            True,
            True,
            False,
        ),
        (
            "Insulin Glargine",
            "injection",
            100.0,
            "units/mL",
            "subcutaneous",
            "insulin glargine",
            "Lantus",
            "00088-2220-00",
            3,
            True,
            True,
            False,
        ),
        (
            "Insulin NPH",
            "injection",
            100.0,
            "units/mL",
            "subcutaneous",
            "insulin NPH",
            "Humulin N",
            "00002-8501-01",
            2,
            False,
            True,
            False,
        ),
        # Tier 4 - Non-Preferred Brand Drugs
        (
            "Esomeprazole",
            "capsule",
            20.0,
            "mg",
            "oral",
            "esomeprazole magnesium",
            "Nexium",
            "00186-5020-31",
            4,
            True,
            False,
            True,
        ),
        (
            "Esomeprazole",
            "capsule",
            40.0,
            "mg",
            "oral",
            "esomeprazole magnesium",
            "Nexium",
            "00186-5040-31",
            4,
            True,
            False,
            True,
        ),
        (
            "Celecoxib",
            "capsule",
            100.0,
            "mg",
            "oral",
            "celecoxib",
            "Celebrex",
            "00025-1525-31",
            4,
            True,
            False,
            True,
        ),
        (
            "Celecoxib",
            "capsule",
            200.0,
            "mg",
            "oral",
            "celecoxib",
            "Celebrex",
            "00025-1525-51",
            4,
            True,
            False,
            True,
        ),
        # Tier 5 - Specialty Drugs (highest cost, most restrictions)
        (
            "Adalimumab",
            "injection",
            40.0,
            "mg/0.8mL",
            "subcutaneous",
            "adalimumab",
            "Humira",
            "0074-3799-02",
            5,
            True,
            True,
            True,
        ),
        (
            "Etanercept",
            "injection",
            25.0,
            "mg/0.5mL",
            "subcutaneous",
            "etanercept",
            "Enbrel",
            "58406-425-01",
            5,
            True,
            True,
            True,
        ),
        (
            "Etanercept",
            "injection",
            50.0,
            "mg/mL",
            "subcutaneous",
            "etanercept",
            "Enbrel",
            "58406-435-01",
            5,
            True,
            True,
            True,
        ),
        (
            "Infliximab",
            "injection",
            100.0,
            "mg",
            "intravenous",
            "infliximab",
            "Remicade",
            "57894-030-01",
            5,
            True,
            True,
            True,
        ),
        (
            "Rituximab",
            "injection",
            100.0,
            "mg/10mL",
            "intravenous",
            "rituximab",
            "Rituxan",
            "50242-051-21",
            5,
            True,
            True,
            True,
        ),
        (
            "Trastuzumab",
            "injection",
            150.0,
            "mg",
            "intravenous",
            "trastuzumab",
            "Herceptin",
            "50242-134-01",
            5,
            True,
            True,
            True,
        ),
        # Additional Common Medications
        (
            "Omeprazole",
            "capsule",
            20.0,
            "mg",
            "oral",
            "omeprazole",
            "Prilosec",
            "00186-1080-05",
            1,
            False,
            False,
            False,
        ),
        (
            "Pantoprazole",
            "tablet",
            40.0,
            "mg",
            "oral",
            "pantoprazole sodium",
            "Protonix",
            "00008-0841-81",
            2,
            False,
            False,
            False,
        ),
        (
            "Levothyroxine",
            "tablet",
            25.0,
            "mcg",
            "oral",
            "levothyroxine sodium",
            "Synthroid",
            "0074-7060-90",
            1,
            False,
            False,
            False,
        ),
        (
            "Levothyroxine",
            "tablet",
            50.0,
            "mcg",
            "oral",
            "levothyroxine sodium",
            "Synthroid",
            "0074-5672-90",
            1,
            False,
            False,
            False,
        ),
        (
            "Levothyroxine",
            "tablet",
            75.0,
            "mcg",
            "oral",
            "levothyroxine sodium",
            "Synthroid",
            "0074-5673-90",
            1,
            False,
            False,
            False,
        ),
        (
            "Levothyroxine",
            "tablet",
            100.0,
            "mcg",
            "oral",
            "levothyroxine sodium",
            "Synthroid",
            "0074-5674-90",
            1,
            False,
            False,
            False,
        ),
        (
            "Warfarin",
            "tablet",
            1.0,
            "mg",
            "oral",
            "warfarin sodium",
            "Coumadin",
            "00056-0169-75",
            1,
            True,
            True,
            False,
        ),
        (
            "Warfarin",
            "tablet",
            2.0,
            "mg",
            "oral",
            "warfarin sodium",
            "Coumadin",
            "00056-0170-75",
            1,
            True,
            True,
            False,
        ),
        (
            "Warfarin",
            "tablet",
            5.0,
            "mg",
            "oral",
            "warfarin sodium",
            "Coumadin",
            "00056-0171-75",
            1,
            True,
            True,
            False,
        ),
    ]

    conn = sqlite3.connect(db_path)

    conn.executemany(
        """
        INSERT INTO drug_rules (
            name, dosage_form, strength_qty, strength_unit, route,
            generic_name, brand_name, ndc, formulary_tier,
            prior_authorization, quantity_limit, step_therapy
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """,
        sample_drugs,
    )

    conn.commit()

    # Log comprehensive statistics
    cursor = conn.execute("SELECT COUNT(*) FROM drug_rules")
    count = cursor.fetchone()[0]
    logger.info(f"Loaded {count} drugs into comprehensive formulary database")

    # Show tier distribution
    logger.info("Formulary tier distribution:")
    cursor = conn.execute(
        "SELECT formulary_tier, COUNT(*) FROM drug_rules \n        GROUP BY formulary_tier ORDER BY formulary_tier"
    )
    for tier, count in cursor.fetchall():
        tier_names = {
            1: "Generic",
            2: "Preferred Brand",
            3: "Non-Preferred Brand",
            4: "Non-Preferred Brand",
            5: "Specialty",
        }
        logger.info(f"  Tier {tier} ({tier_names.get(tier, 'Unknown')}): {count} drugs")

    # Show restriction statistics
    cursor = conn.execute("SELECT COUNT(*) FROM drug_rules WHERE prior_authorization = 1")
    pa_count = cursor.fetchone()[0]
    cursor = conn.execute("SELECT COUNT(*) FROM drug_rules WHERE quantity_limit = 1")
    ql_count = cursor.fetchone()[0]
    cursor = conn.execute("SELECT COUNT(*) FROM drug_rules WHERE step_therapy = 1")
    st_count = cursor.fetchone()[0]

    logger.info("Coverage restrictions:")
    logger.info(f"  Prior Authorization required: {pa_count} drugs")
    logger.info(f"  Quantity Limits applied: {ql_count} drugs")
    logger.info(f"  Step Therapy required: {st_count} drugs")

    conn.close()


if __name__ == "__main__":
    db_path = "fastform.db"

    logger.info("Starting comprehensive CMS formulary data ingestion...")
    logger.info("This represents a realistic Medicare Part D formulary with:")
    logger.info("- 5 formulary tiers (Generic to Specialty)")
    logger.info("- Coverage restrictions (PA, QL, ST)")
    logger.info("- Real NDC numbers and brand names")
    logger.info("- Common therapeutic categories")

    # Create database schema
    create_database_schema(db_path)

    # Load comprehensive formulary data
    load_comprehensive_formulary_data(db_path)

    logger.info("\nFormulary data ingestion complete!")
    logger.info(f"Database saved to: {db_path}")
    logger.info("Ready for drug searches and OpenAI integration!")
